export type Post = {
  slug: string;
  title: string;
  shortTitle: string;
  excerpt: string;
  category: string;
  readTime: string;
  date: string;
  keyword: string;
  metaDescription: string;
  body: Section[];
};

export type Section =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "quote"; text: string };

export const posts: Post[] = [
  {
    slug: "website-for-coaches-get-more-clients",
    shortTitle: "Coaches: How to Get More Clients With Your Website",
    title: "Website for Coaches: How to Get More Clients in 2026",
    excerpt: "Stop sending leads to a link-in-bio. Build a coaching website that actually books calls, sells programs and grows your authority on autopilot.",
    category: "Coaches",
    readTime: "7 min read",
    date: "2026-04-22",
    keyword: "website for coaches",
    metaDescription: "A practical guide for coaches: how to build a website that gets more clients, books calls and sells programs in 2026. Real strategies, no fluff.",
    body: [
      { type: "p", text: "If you're a coach in 2026, your Instagram bio is not a business. A 'link in bio' is not a funnel. And a Linktree page is not a website. Yet most coaches — even the ones with 50K+ followers — are still trying to convert audience attention with the digital equivalent of a sticky note." },
      { type: "p", text: "The result is predictable. Lots of DMs, lots of 'how much do you charge?', and very few high-ticket clients who actually pay. The problem isn't your content. The problem is what happens after someone clicks." },
      { type: "h2", text: "Why most coaching websites lose clients" },
      { type: "p", text: "We've audited hundreds of coaching websites at MightBeMedia. The pattern repeats. The site looks beautiful, the colors are on-brand, the photos are crisp — but there's no conversion system underneath. Visitors arrive, read a paragraph about 'my journey', scroll a bit, and leave." },
      { type: "ul", items: [
        "No clear promise in the first 5 seconds",
        "No proof that the coach can actually deliver results",
        "No obvious next step (book a call? buy a program? join a list?)",
        "No way to capture a lead if the visitor isn't ready to buy today",
        "Pricing hidden behind a 'contact me' form that nobody fills",
      ]},
      { type: "h2", text: "The 5 sections every coaching website needs" },
      { type: "h3", text: "1. A specific, outcome-driven hero" },
      { type: "p", text: "The hero section is not the place for a generic 'Welcome to my world' tagline. It's the place to state, in one sentence, who you help and what outcome you deliver. 'I help female founders go from $10K to $50K months without burning out' converts. 'Coach. Speaker. Author.' does not." },
      { type: "h3", text: "2. Proof — not just testimonials" },
      { type: "p", text: "Testimonials are good. Specific results are better. Show before-and-after numbers, client wins with names and faces, screenshots of DMs, podcast features. The brain trusts pattern, not promise." },
      { type: "h3", text: "3. A signature offer page (not a menu)" },
      { type: "p", text: "Coaches who try to sell five programs to five different audiences sell zero. Pick your highest-ticket, highest-impact offer and build a single page around it: who it's for, what they'll get, the transformation, the price, the call-to-action." },
      { type: "h3", text: "4. A lead magnet that does one job" },
      { type: "p", text: "95% of visitors aren't ready to book a call today. So capture them. A short PDF, a workshop replay, a 5-day email sequence — anything that solves one specific problem and gets them on your list." },
      { type: "h3", text: "5. A booking page that removes friction" },
      { type: "p", text: "Use Calendly or SavvyCal. Embed it directly. No 'fill out this form and I'll get back to you in 2 business days'. The moment a hot lead lands, they should be able to pick a time and pay (or qualify) instantly." },
      { type: "h2", text: "The funnel: what actually moves people from visit to client" },
      { type: "p", text: "A coaching website without a funnel is a brochure. A coaching website with a funnel is a sales engine. Here's the structure we build for our coaching clients at MightBeMedia:" },
      { type: "ul", items: [
        "Traffic from Instagram, YouTube, and SEO lands on a specific landing page (not the homepage)",
        "The page makes a single offer — usually a free training, a quiz, or a discovery call",
        "The visitor opts in or books — both flow into your CRM and a follow-up email sequence",
        "Hot leads get a personal message within 1 hour. Warm leads get nurtured for 7-14 days.",
        "Closed clients get onboarded through the same system, no spreadsheets, no chaos",
      ]},
      { type: "quote", text: "A great website doesn't sell coaching. It sorts strangers into buyers — automatically." },
      { type: "h2", text: "SEO for coaches: how to get found on Google" },
      { type: "p", text: "Most coaches ignore SEO and rely 100% on social. That's a mistake. People searching 'business coach for female founders India' or 'fitness coach Mumbai' have buyer intent. They're not scrolling — they're hunting. Rank for those terms and you get clients without posting daily." },
      { type: "p", text: "Start with three to five blog articles targeting your niche keywords. Each post should answer one specific question your dream client is Googling at 11pm. Internal-link them to your offer page. Within 90 days, you'll start seeing organic discovery calls." },
      { type: "h2", text: "The bottom line" },
      { type: "p", text: "Your website should be the hardest-working asset in your business. If it's not generating qualified discovery calls every single week, it's not a website — it's a digital business card. And business cards don't pay your bills." },
      { type: "p", text: "At MightBeMedia, we build conversion-focused coaching websites that turn social audiences into booked calls and paying clients. If you're tired of doing it yourself, let's talk." },
    ],
  },
  {
    slug: "how-gyms-get-more-clients-website",
    shortTitle: "Gyms & Trainers: Get More Clients Through Your Website",
    title: "How Gyms and Fitness Trainers Can Get More Clients Using a Website",
    excerpt: "Reels alone won't fill your gym. Here's the conversion system that turns followers into trial bookings, members and long-term retention.",
    category: "Fitness",
    readTime: "8 min read",
    date: "2026-04-15",
    keyword: "website for gyms and fitness trainers",
    metaDescription: "How gyms and personal trainers can use a website to get more clients, more trials and higher retention. A practical conversion playbook for 2026.",
    body: [
      { type: "p", text: "The fitness industry runs on attention. Reels, transformations, testimonials — every gym and trainer is competing in the same scroll. But attention is not income. The trainers who actually grow their gyms in 2026 aren't the ones with the most reels. They're the ones with the best system after the reel." },
      { type: "h2", text: "Why most gym websites are dead weight" },
      { type: "p", text: "Most gym websites in India look like they were built in 2014. Stock photos of barbells, a generic 'About Us', a contact form nobody fills, and a phone number nobody calls. Meanwhile, your competitor next door is converting Instagram traffic into 30 trial bookings a month — without spending more on ads." },
      { type: "ul", items: [
        "No free trial offer that's easy to claim",
        "No clear pricing — visitors have to ask, so they don't",
        "No social proof from local clients with real transformations",
        "No WhatsApp click-to-chat for the people who just want to talk",
        "No SEO, so when someone searches 'gym near me' you don't show up",
      ]},
      { type: "h2", text: "The conversion system that works for fitness businesses" },
      { type: "h3", text: "1. A free trial as your front door" },
      { type: "p", text: "The number-one offer that converts cold traffic in fitness is a low-friction free trial. 7 days free. One free PT session. Free body composition analysis. Whatever you call it, it should be the loudest button on your homepage. The goal is not to make money on the trial — it's to get them in the door." },
      { type: "h3", text: "2. Transparent pricing (yes, really)" },
      { type: "p", text: "Hiding pricing kills conversions. People assume the worst when you make them work for a number. Show your plans, show what's included, and show one 'most popular' option that pulls the eye. If someone is going to spend ₹15,000 a year on you, they want to know upfront." },
      { type: "h3", text: "3. Real transformations from real members" },
      { type: "p", text: "Stock photos of fit models do nothing. Your actual member, photographed in your actual gym, with their actual results — that's gold. Get permission, get good lighting, and feature 6-10 transformations on the homepage. This is your single most powerful conversion asset." },
      { type: "h3", text: "4. WhatsApp lead capture, not contact forms" },
      { type: "p", text: "Indian users don't fill long forms. They tap WhatsApp. Add a sticky 'Book Free Trial on WhatsApp' button. Pre-fill the message. Route it to a real person — or a chatbot during off-hours. You'll 3-4x your inquiry volume overnight." },
      { type: "h3", text: "5. Local SEO so you show up on 'gym near me'" },
      { type: "p", text: "Set up a Google Business Profile. Optimize it with photos, reviews, and accurate hours. Add location pages on your website ('Gym in Indiranagar', 'PT in Andheri West'). Within 60-90 days, you'll start showing up in the local 3-pack — which drives more high-intent leads than any ad." },
      { type: "h2", text: "Personal trainers: what works differently" },
      { type: "p", text: "If you're a solo trainer (online or offline), your website is your authority play. You're not selling a facility — you're selling yourself. That means proof, story, and method." },
      { type: "ul", items: [
        "Lead with one specific niche (postpartum fitness, fat loss for men 35+, strength for runners)",
        "Show your method — what makes your approach different",
        "Stack proof: certifications, client transformations, podcast features, follower count",
        "Offer a free assessment call or a paid 'starter program' as the entry point",
        "Build an email list with a free training plan PDF",
      ]},
      { type: "quote", text: "Your website should make your best clients pre-sold before they ever message you." },
      { type: "h2", text: "Retention: the part nobody talks about" },
      { type: "p", text: "Most fitness businesses spend 10x more energy acquiring new members than retaining the ones they have. Your website should also serve existing members — class schedules, member portal, progress tracking, referral programs. Retention is where the real revenue lives." },
      { type: "h2", text: "What to do this week" },
      { type: "ul", items: [
        "Audit your homepage: can a stranger book a free trial in under 30 seconds?",
        "Add a sticky WhatsApp button if you don't already have one",
        "Replace stock photos with three real member transformations",
        "Set up your Google Business Profile and ask 10 happy clients for a review",
        "Write down your one signature offer — and make it the loudest thing on the site",
      ]},
      { type: "p", text: "At MightBeMedia, we build conversion-focused websites for gyms, personal trainers and fitness brands. If your reels are popping but your bookings aren't, your funnel is broken — and that's exactly what we fix." },
    ],
  },
  {
    slug: "how-clinics-get-more-patients-from-google",
    shortTitle: "Clinics: How to Get More Patients From Google",
    title: "How Clinics Can Get More Patients From Google in 2026",
    excerpt: "Patients search before they book. Here's how to make sure your clinic shows up first — and converts that search into a real appointment.",
    category: "Healthcare",
    readTime: "8 min read",
    date: "2026-04-08",
    keyword: "website for clinics get more patients",
    metaDescription: "A practical SEO and conversion playbook for clinics and doctors who want more patients from Google. Local SEO, booking systems, trust building.",
    body: [
      { type: "p", text: "When was the last time you booked a doctor's appointment without Googling first? In 2026, every patient does the same thing: search, scan reviews, check the website, decide. If your clinic isn't winning that 30-second decision, you're losing patients to the clinic next door — even if you're a better doctor." },
      { type: "h2", text: "The patient journey nobody talks about" },
      { type: "p", text: "Patients don't decide based on your degrees. They decide based on three things they can verify online in under a minute:" },
      { type: "ul", items: [
        "Can I trust this clinic? (reviews, photos, doctor profiles)",
        "Is it convenient? (location, hours, booking)",
        "Will I be taken care of? (specialization, before-and-after, treatment details)",
      ]},
      { type: "p", text: "Your website and Google Business Profile have to answer all three in seconds. Most clinics fail at all three." },
      { type: "h2", text: "Local SEO: the single highest-ROI thing you can do" },
      { type: "p", text: "Forget national SEO. You're not trying to rank for 'best dermatologist in India'. You want to rank for 'dermatologist in Bandra' or 'hair transplant clinic Delhi'. That's local SEO — and it's where 80% of clinic patients come from." },
      { type: "h3", text: "Step 1: Optimize your Google Business Profile" },
      { type: "p", text: "This is non-negotiable. Claim your profile, fill every field, add 20+ photos (clinic interior, doctors, equipment, procedures), set accurate hours including holidays, list every service category that applies. Then ask every happy patient for a review. Aim for at least 50 reviews with a 4.7+ average. This alone moves the needle more than any website redesign." },
      { type: "h3", text: "Step 2: Build location-specific pages on your website" },
      { type: "p", text: "If you have multiple branches, each branch needs its own page targeting its area. 'Skin Clinic in Indiranagar', 'Hair Treatment in Whitefield'. Each page should have unique content — local landmarks, parking, photos of that specific clinic, doctors at that location. Google rewards specificity." },
      { type: "h3", text: "Step 3: Service-specific landing pages" },
      { type: "p", text: "Don't put all your treatments on one 'Services' page. Each major treatment deserves its own deep-dive page: what it is, who it's for, how it works, how much it costs (yes, ranges), recovery time, before-and-after photos, FAQs. These pages rank for high-intent searches like 'PRP hair treatment cost Mumbai'." },
      { type: "h2", text: "Conversion: turning a Google visit into a booked appointment" },
      { type: "p", text: "Ranking is half the battle. Conversion is the other half. Even with #1 rankings, most clinic websites convert at 1-2% because they make booking hard." },
      { type: "h3", text: "Make booking the loudest thing on every page" },
      { type: "p", text: "A floating 'Book Appointment' button. A WhatsApp click-to-chat. A simple 3-field form (name, phone, preferred time). Multiple touch points, all leading to the same outcome. Don't make patients hunt." },
      { type: "h3", text: "Show your doctors as humans" },
      { type: "p", text: "Profile photos. Short videos. Credentials, but also why they became doctors. Patients don't want a clinic — they want a person they can trust with their body." },
      { type: "h3", text: "Real before-and-after with consent" },
      { type: "p", text: "For dermatology, dental, cosmetic, hair, weight loss — visual proof is everything. Get patient consent, photograph in consistent lighting, and show 6-12 strong before-afters on relevant treatment pages. A single great before-and-after converts more patients than 1,000 words of copy." },
      { type: "h3", text: "Trust signals patients actually scan for" },
      { type: "ul", items: [
        "Years in practice",
        "Number of patients treated",
        "Certifications visible (NABH, ISO, board memberships)",
        "Insurance and payment options",
        "Featured-in logos (newspapers, magazines, TV)",
      ]},
      { type: "quote", text: "Patients don't read websites. They scan for reasons to trust you — or to keep scrolling." },
      { type: "h2", text: "Reviews: the conversion multiplier" },
      { type: "p", text: "A clinic with 12 reviews and a 4.9 rating loses to a clinic with 200 reviews and a 4.6 rating. Volume of social proof matters as much as the average. Build a system: SMS the review link to every patient 24 hours after their appointment. Make it one-tap easy. Watch your bookings climb." },
      { type: "h2", text: "Paid ads: only after the foundation is solid" },
      { type: "p", text: "Don't run Google Ads to a broken website. Fix the conversion system first — booking flow, trust signals, mobile experience. Then layer paid traffic on top of a website that already converts. Otherwise you're just paying Google to send you visitors who bounce." },
      { type: "h2", text: "What to do this month" },
      { type: "ul", items: [
        "Audit and complete your Google Business Profile",
        "Get 20 new patient reviews (with the link, sent 24 hrs post-visit)",
        "Add a sticky WhatsApp + Book Appointment button to every page",
        "Build one strong before-and-after page for your best treatment",
        "Write three location/service pages targeting specific local keywords",
      ]},
      { type: "p", text: "At MightBeMedia, we build SEO-ready, conversion-focused websites for clinics, doctors and hospitals. If patients are searching for what you do but landing on someone else's site, that's a fixable problem." },
    ],
  },
  {
    slug: "instagram-alone-not-enough-for-business",
    shortTitle: "Why Instagram Alone Won't Grow Your Business",
    title: "Why Instagram Alone Is Not Enough to Grow Your Business",
    excerpt: "Followers feel good. They don't pay your bills. Here's why an Instagram-only strategy is fragile — and what a real growth system looks like.",
    category: "Growth",
    readTime: "7 min read",
    date: "2026-03-30",
    keyword: "instagram is not enough for business",
    metaDescription: "Why an Instagram-only strategy fails most businesses, and what a real growth system looks like in 2026. Build assets you actually own.",
    body: [
      { type: "p", text: "There's a generation of business owners in India who think Instagram is their business. They post reels daily, hit 100K followers, get featured on Curly Tales — and still struggle to pay rent. Not because Instagram is bad. Because Instagram alone is fragile." },
      { type: "h2", text: "You don't own your audience on Instagram" },
      { type: "p", text: "Read that again. Every follower you have is a follower Meta lets you reach. Algorithm changes overnight. Reach drops 70% with no warning. Your account gets shadowbanned, hacked, or randomly suspended. And just like that, the 50K audience you spent three years building is unreachable." },
      { type: "p", text: "Compare that to an email list of 5,000 people. You own that list. You can email it tomorrow, next month, or three years from now. Open rates of 30-40%. Conversion rates 10x higher than social. Nobody can take it from you." },
      { type: "h2", text: "The four things Instagram alone can never do" },
      { type: "h3", text: "1. Capture buyer intent" },
      { type: "p", text: "Nobody opens Instagram thinking 'I need to hire a business coach'. They open it to scroll. The audience is in entertainment mode. SEO and Google, on the other hand, are full of people actively searching for solutions. That's where buying happens." },
      { type: "h3", text: "2. Convert at scale without you" },
      { type: "p", text: "Instagram conversion runs through your DMs. Which means you, personally, replying to messages. That's not a business — that's a job. A real growth system converts strangers into customers without you touching every conversation." },
      { type: "h3", text: "3. Build long-term authority that compounds" },
      { type: "p", text: "Reels die in 48 hours. A blog post can rank for years. A YouTube video can generate leads forever. A podcast episode keeps getting downloads. Instagram is a treadmill — you stop posting, growth stops. Real authority assets compound while you sleep." },
      { type: "h3", text: "4. Survive a platform change" },
      { type: "p", text: "TikTok got banned in India. Just like that, lakhs of creators lost their audience, their brand deals, and their income. The same can happen to Instagram. The only protection is platform diversification — owned channels you control." },
      { type: "h2", text: "What a real growth system looks like" },
      { type: "p", text: "A real growth system has multiple, compounding traffic sources feeding into owned assets that convert on autopilot. Here's the structure we build at MightBeMedia:" },
      { type: "ul", items: [
        "Instagram + YouTube for top-of-funnel awareness",
        "SEO blog content for high-intent buyer traffic from Google",
        "A conversion-focused website with clear offers",
        "Email list capture on every page (lead magnet, newsletter)",
        "An email sequence that nurtures and sells while you sleep",
        "Retargeting ads that bring back warm visitors",
      ]},
      { type: "p", text: "Each piece supports the others. Instagram drives followers to your lead magnet. The lead magnet captures emails. Email sells your offer. The website ranks on Google for search-intent traffic. Retargeting catches the people who weren't ready yet. Nothing depends on a single platform." },
      { type: "quote", text: "Build your business on rented land and you'll always be one algorithm change away from zero." },
      { type: "h2", text: "But Instagram still matters" },
      { type: "p", text: "We're not anti-Instagram. It's still one of the best top-of-funnel platforms in India. Reels are the cheapest cold traffic on the internet. The mistake isn't using Instagram — it's stopping there." },
      { type: "p", text: "Use Instagram to attract. Use a lead magnet to capture. Use email to nurture. Use a website to convert. That's the system. Anything less and you're playing with borrowed reach." },
      { type: "h2", text: "The 90-day shift" },
      { type: "p", text: "If your business is 100% Instagram-dependent today, here's the 90-day plan to stop being fragile:" },
      { type: "ul", items: [
        "Day 1-30: Build a one-page conversion website with one clear offer and one lead magnet",
        "Day 30-60: Start an email newsletter, drive your existing audience to it from every reel and bio",
        "Day 60-90: Publish your first 5 SEO blog posts targeting buyer-intent keywords in your niche",
      ]},
      { type: "p", text: "By day 90 you'll have email subscribers you actually own, organic traffic from Google, and a website that converts strangers without your DMs being open 24/7. That's a business." },
      { type: "p", text: "At MightBeMedia, we help businesses move from Instagram-dependent to growth-system-driven. If you're tired of being one algorithm change away from broke, let's build something you actually own." },
    ],
  },
  {
    slug: "turn-website-visitors-into-paying-clients",
    shortTitle: "How to Turn Website Visitors Into Paying Clients",
    title: "How to Turn Website Visitors Into Paying Clients",
    excerpt: "Traffic without conversion is just noise. Here's the structured system we use to turn cold website visitors into paying customers — every time.",
    category: "Conversion",
    readTime: "9 min read",
    date: "2026-03-22",
    keyword: "turn website visitors into paying clients",
    metaDescription: "The exact conversion system we use at MightBeMedia to turn cold website visitors into paying clients. Funnel structure, copy, CTAs and proof.",
    body: [
      { type: "p", text: "Most businesses obsess over traffic. SEO, ads, reels, collabs — anything to get more eyeballs on the website. Then those eyeballs arrive, look around for 12 seconds, and leave. Nothing bought. No email captured. No call booked. Just bandwidth wasted." },
      { type: "p", text: "The problem isn't traffic. The problem is that 99% of websites are not designed to convert — they're designed to look nice. Conversion is a system, not a vibe. Here's how it actually works." },
      { type: "h2", text: "The 5-stage visitor journey" },
      { type: "p", text: "Every visitor goes through five stages on your site, whether you've designed for it or not. Skip one and conversion drops. Nail all five and your same traffic produces 3-5x more revenue." },
      { type: "h3", text: "Stage 1: Hook (first 5 seconds)" },
      { type: "p", text: "Visitors decide whether to stay or leave in 5 seconds. Your hero section has to answer three questions instantly: What is this? Who is it for? What outcome will I get? If you require scrolling to figure out what you do, you've already lost half your visitors." },
      { type: "p", text: "Bad hero: 'Welcome to Acme Solutions — innovative digital experiences.' Good hero: 'We help D2C brands hit ₹1 crore in monthly revenue with conversion-focused websites and ads.' Specificity converts." },
      { type: "h3", text: "Stage 2: Trust (next 30 seconds)" },
      { type: "p", text: "Once you've hooked them, they need a reason to believe you. This is where most websites collapse. Don't tell them you're great — show them. Logos of brands you've worked with. Specific results with numbers. Recognizable testimonials with names and faces. Press mentions. Case studies." },
      { type: "p", text: "The brain trusts patterns. The more proof signals you stack in the first scroll, the faster trust is built." },
      { type: "h3", text: "Stage 3: Clarity (next 60 seconds)" },
      { type: "p", text: "Now they trust you. But what exactly do you sell, and how does it work? This is where you explain your offer, your process, and what's included. Use scannable sections. Use comparison tables. Use process diagrams. The goal is zero confusion." },
      { type: "h3", text: "Stage 4: Decision (next 30 seconds)" },
      { type: "p", text: "Trust + clarity + the right offer = decision. This is where pricing, packages, and the call-to-action live. Be specific about what they get, what it costs, and what happens when they click 'Book a Call'. Friction kills conversion. Remove every unnecessary step." },
      { type: "h3", text: "Stage 5: Action (the click)" },
      { type: "p", text: "The CTA should be impossible to miss. Bright color. Above the fold. Repeated every 2-3 sections. The action itself should be one tap — book a call, claim a trial, message on WhatsApp. Multi-step forms with 8 fields don't convert. Single-click actions do." },
      { type: "h2", text: "The two-CTA strategy" },
      { type: "p", text: "Not every visitor is ready to buy today. So you need two CTAs on every page: a high-commitment primary CTA ('Book Free Strategy Call') and a low-commitment secondary CTA ('Get Free Audit PDF'). The first captures buyers. The second captures everyone else." },
      { type: "p", text: "The secondary CTA flows into an email sequence that nurtures cold leads into warm ones over 7-30 days. This is where 80% of your eventual customers come from — and 95% of websites don't have it." },
      { type: "h2", text: "Copy that converts" },
      { type: "p", text: "Pretty design with bad copy converts at 1%. Average design with great copy converts at 5%. Copy is the conversion lever, not visuals. Three rules:" },
      { type: "ul", items: [
        "Write to one specific person, not 'everyone'",
        "Lead with their problem, not your features",
        "Use their words — read their reviews, DMs, and complaints, then mirror the language back",
      ]},
      { type: "h2", text: "Mobile-first or die" },
      { type: "p", text: "70%+ of your traffic is on mobile. If your site looks great on a 27-inch monitor and broken on a phone, you're losing 70% of your conversion. Test on a real phone. Tap every button. Fill every form. Check load speed. Most sites fail this test — and lose money every single day because of it." },
      { type: "quote", text: "Conversion is not a design problem. It's a clarity problem dressed as a design problem." },
      { type: "h2", text: "The metrics that matter" },
      { type: "p", text: "Stop tracking pageviews. Start tracking these:" },
      { type: "ul", items: [
        "Hero scroll-past rate (do they scroll past your hero, or bounce?)",
        "Lead magnet opt-in rate (capturing the not-ready visitors)",
        "Primary CTA click rate per page",
        "Form completion rate (vs. abandonment)",
        "Visitor-to-call rate (the only number that matters at the bottom)",
      ]},
      { type: "p", text: "Optimize each stage independently. A 1% improvement at every stage compounds into a 30-50% revenue lift — without spending a rupee more on traffic." },
      { type: "h2", text: "The 30-day conversion lift checklist" },
      { type: "ul", items: [
        "Rewrite your hero to a specific outcome for a specific person",
        "Add three pieces of social proof above the fold",
        "Add a lead magnet + email capture as your secondary CTA",
        "Simplify your primary form to 3 fields max",
        "Test your full mobile flow on a real phone",
        "Add WhatsApp click-to-chat for Indian audiences",
        "Set up basic analytics — track visitor-to-lead, not pageviews",
      ]},
      { type: "p", text: "Do those seven things and most websites see conversion double in 30 days. Not because of magic. Because most websites are leaking visitors at every stage and nobody's plugging the holes." },
      { type: "p", text: "At MightBeMedia, this is exactly what we do. We don't build websites — we build revenue systems that turn traffic into paying clients. If your traffic is good but your bookings aren't, the funnel is broken. Let's fix it." },
    ],
  },
];
